name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-nodejs-app:${{ github.sha }} .

      - name: Run Trivy scan for vulnerabilities
        uses: aquasecurity/trivy-action@v0.16
        with:
          image-ref: my-nodejs-app:${{ github.sha }}
          
      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-nodejs-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-nodejs-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-nodejs-app:${{ github.sha }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
